FROM node:24-alpine AS build
WORKDIR /app
COPY package*.json ./
COPY apps/web/package.json apps/web/package.json
COPY services/api-gateway/package.json services/api-gateway/package.json
COPY services/auth-service/package.json services/auth-service/package.json
COPY services/place-service/package.json services/place-service/package.json
COPY services/review-service/package.json services/review-service/package.json
COPY packages/shared-types/package.json packages/shared-types/package.json
RUN npm ci
COPY . .
ARG WORKSPACE
RUN npm run build -w ${WORKSPACE}

FROM node:24-alpine
WORKDIR /app
COPY --from=build /app /app
ARG WORKSPACE
ENV SERVICE_WORKSPACE=${WORKSPACE}
CMD npm run start -w ${SERVICE_WORKSPACE}
